/*
 * Copyright © 2015 Stefan Niederhauser (nidin@gmx.ch)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package guru.nidi.graphviz.engine;

import com.eclipsesource.v8.V8;
import guru.nidi.graphviz.service.DefaultExecutor;
import guru.nidi.graphviz.service.SystemUtils;
import org.apache.commons.exec.CommandLine;
import org.apache.commons.io.FileUtils;
import org.junit.jupiter.api.*;

import java.io.File;
import java.io.IOException;
import java.lang.reflect.Field;
import java.nio.file.Files;
import java.util.concurrent.*;

import static guru.nidi.graphviz.engine.Format.SVG;
import static guru.nidi.graphviz.engine.Format.SVG_STANDALONE;
import static org.hamcrest.CoreMatchers.startsWith;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assertions.fail;
import static org.mockito.Matchers.any;
import static org.mockito.Mockito.doAnswer;
import static org.mockito.Mockito.mock;

class EngineTest {
    private static final String START1_7 =
            line("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>") +
                    line("<!DOCTYPE svg PUBLIC \"-//W3C//DTD SVG 1.1//EN\"") +
                    line(" \"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd\">") +
                    line("<!-- Generated by graphviz version 2.40.1 (20161225.0304)") +
                    line(" -->") +
                    line("<!-- Title: g Pages: 1 -->") +
                    "<svg";
    private static File temp;

    @BeforeAll
    static void init() throws IOException {
        temp = new File(System.getProperty("java.io.tmpdir"), "engineTest");
        FileUtils.deleteDirectory(temp);
        temp.mkdir();
    }

    @AfterEach
    void end() {
        Graphviz.releaseEngine();
    }

    @Test
    void jdk() {
        Graphviz.useEngine(new GraphvizJdkEngine());
        assertThat(Graphviz.fromString("graph g {a--b}").render(SVG_STANDALONE).toString(), startsWith(START1_7));
    }

    @Test
    void server() {
        GraphvizServerEngine.stopServer();
        try {
            Graphviz.useEngine(new GraphvizServerEngine().useEngine(new GraphvizV8Engine()));
            assertThat(Graphviz.fromString("graph g {a--b}").render(SVG_STANDALONE).toString(), startsWith(START1_7));
        } finally {
            GraphvizServerEngine.stopServer();
        }
    }

    @Test
    void v8() {
        Graphviz.useEngine(new GraphvizV8Engine());
        assertThat(Graphviz.fromString("graph g {a--b}").render(SVG_STANDALONE).toString(), startsWith(START1_7));
    }

    @Test
    void v8WithoutPath() throws Exception {
        assertNativeLibs(System.getProperty("user.home"), () -> {
            Graphviz.useEngine(new GraphvizV8Engine());
        });
    }

    @Test
    void v8WithPath() throws Exception {
        final String tmpDir = System.getProperty("java.io.tmpdir");
        assertNativeLibs(tmpDir, () -> {
            Graphviz.useEngine(new GraphvizV8Engine(tmpDir));
        });
    }

    private void assertNativeLibs(String basedir, Runnable task) throws ReflectiveOperationException {
        final File[] libs = new File[]{
                new File(basedir, "libj2v8_linux_x86_64.so"),
                new File(basedir, "libj2v8_macosx_x86_64.dylib"),
                new File(basedir, "libj2v8_win32_x86.dll"),
                new File(basedir, "libj2v8_win32_x86_64.dll"),
        };
        for (final File lib : libs) {
            lib.delete();
        }
        final Field loaded = V8.class.getDeclaredField("nativeLibraryLoaded");
        loaded.setAccessible(true);
        loaded.setBoolean(null, false);
        task.run();
        for (final File lib : libs) {
            if (lib.exists()) {
                return;
            }
        }
        fail("No native library found");
    }

    @Test
    void multiV8() throws InterruptedException {
        Graphviz.useEngine(new GraphvizV8Engine());
        final ExecutorService executor = Executors.newFixedThreadPool(2);
        for (int i = 0; i < 2; i++) {
            executor.submit(() -> {
                Graphviz.fromString("graph g {a--b}").render(SVG).toString();
                Graphviz.releaseEngine();
            });
        }
        executor.shutdown();
        executor.awaitTermination(60, TimeUnit.SECONDS);
    }

    @Test
    void cmdLine() throws IOException, InterruptedException {
        final File dotFile = setUpFakeDotFile();
        final DefaultExecutor cmdExecutor = setUpFakeStubCommandExecutor();

        final String envPath = dotFile.getParent();
        Graphviz.useEngine(new GraphvizCmdLineEngine(envPath, cmdExecutor));

        assertThat(Graphviz.fromString("graph g {a--b}").render(SVG_STANDALONE).toString(), startsWith(START1_7));
    }

    /**
     * Test to check if we can set the output path and name of the dot file
     */
    @Test
    void cmdLineOutputDotFile() throws IOException, InterruptedException {
        final File dotFile = setUpFakeDotFile();
        final DefaultExecutor cmdExecutor = setUpFakeStubCommandExecutor();

        final String envPath = dotFile.getParent();

        final File dotOutputFolder = new File(temp, "out");
        dotOutputFolder.mkdir();
        final String dotOutputName = "test123";

        // Configure engine to output the dotFile to dotOutputFolder
        final GraphvizCmdLineEngine engine = new GraphvizCmdLineEngine(envPath, cmdExecutor);
        engine.setDotOutputFile(dotOutputFolder.getAbsolutePath(), dotOutputName);

        Graphviz.useEngine(engine);

        // Do execution
        Graphviz.fromString("graph g {a--b}").render(SVG_STANDALONE).toString();

        assertTrue(new File(dotOutputFolder.getAbsolutePath(), dotOutputName + ".dot").exists());
    }

    private File setUpFakeDotFile() throws IOException {
        final String filename = SystemUtils.executableName("dot");
        final File dotFile = new File(temp, filename);
        dotFile.createNewFile();
        dotFile.setExecutable(true);
        return dotFile;
    }

    private DefaultExecutor setUpFakeStubCommandExecutor() throws IOException, InterruptedException {
        final DefaultExecutor cmdExecutor = mock(DefaultExecutor.class);
        doAnswer(invocationOnMock -> {
            final File workingDirectory = invocationOnMock.getArgumentAt(1, File.class);
            final File svgInput = new File(getClass().getClassLoader().getResource("outfile1.svg").getFile());
            final File svgOutputFile = new File(workingDirectory.getAbsolutePath() + "/outfile.svg");
            Files.copy(svgInput.toPath(), svgOutputFile.toPath());
            return null;
        }).when(cmdExecutor).execute(any(CommandLine.class), any(File.class));
        return cmdExecutor;
    }

    private static String line(String s) {
        return s + System.getProperty("line.separator");
    }
}
